name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "KBOT_TOKEN=${{ secrets.__KBOT_TOKEN }}" >> $GITHUB_ENV
          echo "KCHAT_ID=${{ secrets.__KCHAT_ID }}" >> $GITHUB_ENV
      
      - name: Debug secrets
        run: |
          echo "KBOT_TOKEN=${{ secrets.__KBOT_TOKEN }}"
          echo "KCHAT_ID=${{ secrets.__KCHAT_ID }}"

      - name: Run tests
        env:
          KBOT_TOKEN: ${{ secrets.__KBOT_TOKEN }}
          KCHAT_ID: ${{ secrets.__KCHAT_ID }}
        run: |
          python -c "import os; print('KBOT_TOKEN:', os.getenv('KBOT_TOKEN')); print('KCHAT_ID:', os.getenv('KCHAT_ID'))"
          python run_tests.py
